plugins {
    id 'java'
}

group = 'horry'
version = '1.1.0'

repositories {
    mavenCentral()
    maven { url 'https://maven.anuke.com/releases' }
    maven { url 'https://jitpack.io' }
}

dependencies {
    compileOnly "mindustry:core:v146"
    compileOnly "mindustry:desktop:v146"
    compileOnly "arc:arc-core:v146"
}

jar {
    archiveFileName = "ip_switch.jar"
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes 'Main-Class': 'horry.ipswitch.IpSwitchMod'
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}
