plugins {
    id 'java'
}

group = 'horry'
version = '1.1.0'

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
    compileOnly "com.github.Anuken.MindustryJitpack:core:master-SNAPSHOT"
    compileOnly "com.github.Anuken.Arc:arc-core:master-SNAPSHOT"
}

jar {
    archiveFileName = "ip_switch.jar"
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes 'Main-Class': 'horry.ipswitch.IpSwitchMod'
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}
